---
aws_cred_profile: "la-test"

# password for ssh key - ~/.ssh/{{ clusterid }}.{{ dns_domain }}
sshkey_password: 'O^4rXuG5^rQV73G'

clusterid: "la-test"
dns_domain: "geixunsapoc02.com"
aws_region: "us-west-2"

vpc_cidr: "172.16.0.0/16"

subnets_public_cidr:
  - 172.16.0.0/24
  - 172.16.1.0/24
  - 172.16.2.0/24

subnets_private_cidr:
  - 172.16.16.0/20
  - 172.16.32.0/20
  - 172.16.48.0/20

ec2_type_bastion: "t2.medium"
ec2_type_captain: "m5.2xlarge"
ec2_type_infra: "m5.2xlarge"
ec2_type_node: "m5.2xlarge"
ec2_type_cns: "m5.2xlarge"

rhel_release: "rhel-7.5"
