---
- name: "Obtain currently enabled repos"
  shell: 'subscription-manager repos --list-enabled | sed -ne "s/^Repo ID:[^a-zA-Z0-9]*\(.*\)/\1/p"'
  register: enabled_repos

- name: "Enable specified repositories not already enabled"
  command: "subscription-manager repos --enable={{ item }}"
  with_items:
    - "{{ openshift_deploy_repos | difference(enabled_repos.stdout_lines) }}"
  register: subscribe_repos
  until: subscribe_repos | succeeded

- name: "Be sure all pre-req provider packages are installed"
  yum: name={{item}} state=installed
  with_items:
    - "{{ openshift_deploy_packages }}"

- name: Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

- name: be sure all pre-req provider EPEL packages are installed
  yum: name={{item}} state=installed
  with_items:
    - "{{ openshift_deploy_epel_packages }}"
