---
  - name: "Set dual view dns group"
    set_fact:
      named_views_hostgroup: "cluster_hosts"
      named_views_infragroup: "infra_hosts"

  - name: "Setting up views"
    template:
      dest: /tmp/named_views.yml
      src: ./templates/named_views.template
      force: true
    delegate_to: localhost
