---
- name: Check to see if heketi secret is already created
  command: "oc get secrets"
  register: oc_secrets

- name: Check to see if storage class is already created
  command: "oc get storageclass"
  register: storage_class

- name: Remove heketi secret from OCP
  command: "oc delete secret heketi-secret"
  when: "'heketi-secret' in oc_secrets.stdout"

- name: Remove storage class from OCP
  command: "oc delete storageclass crs-slow-st1"
  when: "'crs-slow-st1' in storage_class.stdout"
