---
sudo: required

services:
  - docker

cache:
  - pip

language: python
python:
  - "2.7"
  - "3.5"

env:
  global:
    - secure: Uaq7rWx2tb3nznm48+Ck9ALoJ8o+Kdkj0LWWj129urBAb2F0HjiXTO3DaTCa0qc/CM5qTM/+bX1hPvws+niwmxjayQTGGKYCMWPyKKdoubNM//6Uu1y5a0QhwVFCaMFBoHv3GVmBwnPRi6qd9T6VYAaGyYs/Vpo29iSqpEhXx8KD58MohAimpxikr7NkL2gpLByAysER9+MtFkR/R8ss+Drw19kRE1JStRB0EJiRyIY+g3Hy+EidIZ3OFLBnrQK+kfQUL8PoHLPOiYOQlWNPLL3ZZGSc/PUUSrCz593NyeJpXfvaK4Jyk8ol5dfLcBiAiwwNLVC2BuheHIUL1pFj69YpNmAHPfLIdlBlJJFFkX5dx9QUlmb337QdIOXQwyBRppgiPrv09oSGGtkoW3GF32VUESdtvtF1DgdY3e5/Cce5nnPYv8AkQ3aiZUZ5RSDREBA6c/ZMaREqQnrTop5M034o+yKyBhdVFwO1QcqaEeVdIJB8OR148w3F+7aOZBRqq1GNMowmEjcLje0T7ZzBUQcIC+16eHZxtd9E9vzNTPFNfwsl/OGDUMdgpXT4C5nhQw8givVEWuB/UVs+aTNSsTAJbKN0zTED30pWuQuvRUcsr4NEbmMTcNItMgmuhb3/Ej6qeacmoGkqCMODG4xmCYyRWADoTRXN2yOLcdFJp6U=
    - CI_CONCURRENT_JOBS=1
  matrix:
    - RUN_OPENSTACK_CI=false
    - RUN_OPENSTACK_CI=true

matrix:
  exclude:
    - python: "3.5"
      env: RUN_OPENSTACK_CI=true

install:
  - ci/install-tox.sh
  - ci/openstack/install.sh

script:
  - ci/run-tox.sh
  - ci/openstack/provision.sh
  - travis_wait 40 ci/openstack/install-openshift.sh
  - ci/openstack/validate.sh

after_script:
  - ci/openstack/teardown.sh
