---
sudo: required

services:
  - docker

cache:
  - pip

language: python
python:
  - "2.7"
  - "3.5"

env:
  global:
    - secure: glCEAFal3DrjvxbXa5u/GdNQFu/p2dU5VdupxoCiSjeltGlS/fPiZdXZjhlgjiOpaGoPh/AWtkXqiJXAzq+vKYRIFIg6AolPoY7+AQWmOsRp/p6f+EvLw4y2gqXniKyYr00T9afb1zW2tJebdqyMN3B1metgnV6O6rp5tooFlSCqJJDEczdo+KauK5ATfApS6kgFSsfwmFTdFg0MkV6MUGFpHZgvo78xCHWd3/ySlckGNJsq0s3lUafKyzfMegyWwVIyHBNUUKffLawatdZr19A2txEOHrcmJ6AOuJlshvFti2l83VFBm1VvqNWf6Q7KUY5Ee8EO7K7MCOEe/v5VZIt8liizYmie/Ca6b2I/P94iY+9qsS/r1Jh/d0gtFhVt8kJoIHMTwROcz919JZU2Kyn1pTu6l8/7y4zPyouuyewnwLEX9TWKmXYmhLsbWeH3qVKI2w21nSiPpGJo/dT1BRxaBICrAL4HPvSvgAM5bO7/aTh8qhUlsS23lsE9u4MW20HHiZSHpwdDOsQWQnzSZsEjNLOiqHAw9rYJbaqXo01K6ftypLHdQpBP8nq0Az+D2c4Vwcq4uXV23/5TraS3jX1HKsMo5anLc81UfXs6+wXQ86tIKIq4qBeKrNekVWDkBEu9lCQ3eHWLU5jhVo0GjDg2ZSRN6D9L3ZG4pkCadzE=
    - CI_CONCURRENT_JOBS=1
  matrix:
    - RUN_OPENSTACK_CI=false
    - RUN_OPENSTACK_CI=true

matrix:
  exclude:
    - python: "3.5"
      env: RUN_OPENSTACK_CI=true

install:
  - ci/install-tox.sh
  - ci/openstack/install.sh

script:
  - ci/run-tox.sh
  - ci/openstack/provision.sh
  - travis_wait 40 ci/openstack/install-openshift.sh
  - ci/openstack/validate.sh

after_script:
  - ci/openstack/teardown.sh
