---
- name: Register EC2 instances to internet-facing captain ELB
  ignore_errors: yes
  ec2_elb:
    instance_id: "{{ item.tagged_instances[0].id }}"
    ec2_elbs: "{{ elbextcaptain.elb.name }}"
    region: "{{ aws_region }}"
    state: present
  with_items:
    - "{{ ec2captain.results }}"
  register: test
  failed_when: "'InvalidInstanceID.NotFound' in test"

- name: Register EC2 instances to internal captain ELB
  ignore_errors: yes
  ec2_elb:
    instance_id: "{{ item.tagged_instances[0].id }}"
    ec2_elbs: "{{ elbintcaptain.elb.name }}"
    region: "{{ aws_region }}"
    state: present
  with_items:
    - "{{ ec2captain.results }}"
  register: test
  failed_when: "'InvalidInstanceID.NotFound' in test"

- name: Register EC2 instances to internet-facing infra ELB
  ignore_errors: yes
  ec2_elb:
    instance_id: "{{ item.tagged_instances[0].id }}"
    ec2_elbs: "{{ elbextinfra.elb.name }}"
    region: "{{ aws_region }}"
    state: present
  with_items:
    - "{{ ec2infra.results }}"
  register: test
  failed_when: "'InvalidInstanceID.NotFound' in test"
