---
- name: "Retrive credentials from env vars"
  ignore_errors: true
  set_fact:
    aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
    region: "{{ lookup('env','AWS_REGION') }}"

- name: "Retrive credentials from creds file"
  set_fact:
    aws_access_key: "{{ lookup('ini', 'aws_access_key_id section={{ credsprofile }} file=~/.aws/credentials') }}"
    aws_secret_key: "{{ lookup('ini', 'aws_secret_access_key section={{ credsprofile }} file=~/.aws/credentials') }}"
    region: "{{ lookup('ini', 'region section={{ credsprofile }} file=~/.aws/credentials') }}"

- debug:
    msg:
      - 'Error in env; Unable to discover AWS_ACCESS_KEY_ID'
  when: not aws_access_key
  failed_when: not aws_access_key

- debug:
    msg:
      - 'Error in env; Unable to discover AWS_SECRET_ACCESS_KEY'
  when: not aws_secret_key
  failed_when: not aws_secret_key

- name: 'Set fact: arg for lookup queries'
  set_fact:
    creds:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: "{{ region }}"
