---
- name: "Create AWS SecurityGroup (CNS)"
  ec2_group:
    name: "cns"
    description: "cns"
    purge_rules: false
    purge_rules_egress: false
    region: "{{ region }}"
    vpc_id: "{{ vpc.vpc.id }}"
  register: sgcns

- name: "Creating AWS SecurityGroup rules (CNS)"
  ec2_group:
    name: "cns"
    description: "cns"
    region: "{{ region }}"
    vpc_id: "{{ vpc.vpc.id }}"
    rules:
      - proto: tcp
        from_port: 2222
        to_port: 2222
        group_name: "cns"
      - proto: tcp
        from_port: 24007
        to_port: 24008
        group_name: "cns"
      - proto: tcp
        from_port: 49152
        to_port: 49664
        group_name: "cns"
