---
- name: Create VPC
  ec2_vpc_net:
    state: present
    cidr_block: "{{ cidrvpc }}"
    dhcp_opts_id: "{{ vpcdhcpopts.dhcp_options_id }}"
    name: "{{ clusterid }}"
    region: "{{ region }}"
  retries: 3
  delay: 5
  register: vpc
