---
- name: "Create VPC DHCP Options"
  ec2_vpc_dhcp_options:
    domain_name: "{{ dhcp_domainname }}"
    region: "{{ aws_region }}"
    dns_servers:
      - AmazonProvidedDNS
    inherit_existing: False
  retries: 3
  delay: 3
  register: vpcdhcpopts
