---
openshift_deployment_type: openshift-enterprise
openshift_release: v3.5
openshift_master_default_subdomain: "apps.{{ env_id }}.{{ public_dns_domain }}"

# NOTE(shadower): do not remove this line, otherwise the default node labels
# won't be set up.
openshift_node_labels: "{{ openstack.metadata.node_labels }}"

osm_default_node_selector: 'region=primary'
