---
- name: install haproxy
  package: name=haproxy state=present

- name: configure haproxy
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg

- name: start and enable haproxy service
  service: name=haproxy state=started enabled=yes
