---
- hosts: localhost
  gather_facts: yes
  vars_files:
  - vars/main.yaml
  roles:
  # Group systems
  - instance-groups

- include: ../../../playbooks/empty-dir-quota.yaml

- hosts: single_master
  gather_facts: yes
  vars_files:
  - vars/main.yaml
  roles:
  - instance-groups
  - storage-class-configure
