---
- name: create the docker-storage-setup config file
  template:
    src: "{{ role_path }}/templates/docker-storage-setup.j2"
    dest: /etc/sysconfig/docker-storage-setup
    owner: root
    group: root
    mode: 0644

- name: stop docker
  service: name=docker state=stopped

- name: run docker-storage-setup
  command: docker-storage-setup

- name: start docker
  service: name=docker state=started
