---
- name: create HOT stack template prefix
  register: stack_template_pre
  tempfile:
    state: directory
    prefix: casl-ansible

- name: set template paths
  set_fact:
    stack_template_path: "{{ stack_template_pre.path }}/stack.yaml"
    server_template_path: "{{ stack_template_pre.path }}/server.yaml"
    user_data_template_path: "{{ stack_template_pre.path }}/user-data"

- name: generate HOT stack template from jinja2 template
  template:
    src: heat_stack.yaml.j2
    dest: "{{ stack_template_path }}"

- name: generate HOT server template from jinja2 template
  template:
    src: heat_stack_server.yaml.j2
    dest: "{{ server_template_path }}"

- name: generate user_data from jinja2 template
  template:
    src: user_data.j2
    dest: "{{ user_data_template_path }}"

- name: create stack
  ignore_errors: False
  register: stack_create
  os_stack:
    name: "{{ stack_name }}"
    state: present
    template: "{{ stack_template_path }}"
    wait: yes

- name: cleanup temp files
  file:
    path: "{{ stack_template_pre.path }}"
    state: absent
